# Generated by Django 5.1.6 on 2025-03-23 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vnext_app', '0003_alter_post_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='contest',
            new_name='content',
        ),
        migrations.AddField(
            model_name='post',
            name='title',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
