# Generated by Django 5.1.6 on 2025-03-23 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vnext_app', '0003_alter_post_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='contest',
            new_name='content',
        ),
    ]
