# Generated by Django 5.1.6 on 2025-03-23 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vnext_app', '0004_rename_contest_post_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='user',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='like',
            name='user',
            field=models.CharField(max_length=100),
        ),
    ]
